Library view book details
wolox-training/eva-swift pull request #4
Opened 2018-11-09 20:14 UTC by emmanuelhcpk

## Summary ##

**Trello card**: https://trello.com/b/THE_PROJECT_BOARD/THE_CARD

A brief description of the pull request

## Screenshots ##

### iPhone 5c/5/5s

Drag and drop screen shots

### iPhone 6/7

Drag and drop screen shots

### iPhone 6+/7+

Drag and drop screen shots

## Screencast ##

Drag and drop gif screen cast:
 * If you can prove the functionality using the simulator use [LICECap](http://www.cockos.com/licecap/) to record the screencast.
 * If the feature you are adding must be tested in a real device (you depend on bluetooth for example) use QuickTime to record the screencast. Check [this](http://www.tekrevue.com/tip/record-iphone-screen-quicktime/) tutorial on how to record a screencast with Quicktime and then check [this](https://gist.github.com/dergachev/4627207) tutorial on how to convert the `.mov` to `.gif` file in order to be able to attach it to the pull request.

## Known issues ##

If there are known issues or missing functionality report them

2018-11-12 17:06 UTC, acid-wolox requested changes
Great work, Emma! I left some comments and requests for changes before we take it to the main branch.

(also, I listened to the Dead Kennedys the whole time while reading your code 😈 )

2018-11-12 17:06 UTC, acid-wolox commented on Project/BookDetail/BookDetailsViewController.swift
> +
Maybe delete these additional spaces, as they are all private attributes?

2018-11-12 17:06 UTC, acid-wolox commented on Project/BookDetail/Comments/CommentViewController.swift
> +    private var _view: CommentListView = CommentListView.loadFromNib()!
The right order for methods and attributes should be:

- Private and public attributes
- Inits
- Controller overriden methods, like viewDidLoad
- Table view delegate methods (you can even separate these ones into a new extension, in this same file)

2018-11-12 17:06 UTC, acid-wolox commented on Project/BookDetail/Comments/CommentViewController.swift
> +        super.didReceiveMemoryWarning()
Why are you trying to keep this method in your class? It seems to me it just calls its parent method and nothing else. Maybe you can delete it and add it when and if you need it?

2018-11-12 17:06 UTC, acid-wolox commented on Project/BookDetail/Detail/DetailsView.swift
> +    }
Delete this `didSet` if you don't plan on using it.

2018-11-12 17:06 UTC, acid-wolox commented on Project/BookDetail/Detail/DetailsViewController.swift
> +    init(_ viewModel : BookViewModel) {
Add a space here.

2018-11-12 17:06 UTC, acid-wolox commented on Project/BookDetail/Detail/DetailsViewController.swift
> +        _view.year.text = _viewModel.year
I think this will change when the viewModel gets its updated and reactive way of getting the data. It's ok for now.

2018-11-12 17:06 UTC, acid-wolox commented on Project/BookDetail/Detail/DetailsViewController.swift
> +        super.didReceiveMemoryWarning()
Same as before, I don't think you need this method.

2018-11-12 17:06 UTC, acid-wolox commented on Project/BookDetail/Detail/DetailsViewController.swift
> +        //view.backgroundColor = .backgroundColor
Maybe I'm being picky, but commented code shouldn't be merged into `master`. You can comment on functionality and make some descriptions, but if you need this code you can always check previous versions; you already pushed so it's gonna stay in the repository.

2018-11-12 17:06 UTC, acid-wolox commented on Project/BookViewModel.swift
> +    init(book : Book) {
Add a space here.

2018-11-12 17:06 UTC, acid-wolox commented on Project/Library/BooksCell/BooksCellView.swift
Remove this space.

2018-11-12 17:06 UTC, acid-wolox commented on Project/Library/LibraryViewController.swift
> +    }
Is this method override needed? Is it going to be used soon or something like that?

2018-11-12 17:06 UTC, acid-wolox commented on Project/Library/LibraryViewController.swift
> +        if(!book.isLoad){// prevent re fetching the book image
I think you could ask this in other way (for example, if the imageLoad is not `nil` or something like that).

2018-11-12 17:06 UTC, acid-wolox commented on Project/Library/LibraryViewController.swift
> +        }else{
`} else {`

2018-11-12 17:06 UTC, acid-wolox commented on Project/Library/LibraryViewController.swift
> +            _viewModel.loadBooks()
Awesome implementation!

2018-11-12 17:06 UTC, acid-wolox commented on Project/Library/LibraryViewModel.swift
> +    init(booksRepository : BooksRepository = NetworkingBootstrapper.shared.createBooksRepository() ) {
Add a space here.

2018-11-12 17:06 UTC, acid-wolox commented on Project/Library/LibraryViewModel.swift
> +    //private var books : [Book] = []
Delete this if it's not being used anymore.

2018-11-12 17:06 UTC, acid-wolox commented on Project/Library/LibraryViewModel.swift
> +    private var currentPage : Int  = 1
This is just a suggestion, but the code is usually more readable when it's grouped by access type. You'll see what I mean when you have like a thousand attributes and you have to find a particular one. Also remember the syntax convention for the `:` in Swift (`cheese: Food`, for example). 

My suggestion:
```private let _books = MutableProperty<[BookViewModel]>([])
private let booksRepository : BooksRepository
private var currentPage : Int  = 1

public let books:Property<[BookViewModel]>

init(booksRepository : BooksRepository = NetworkingBootstrapper.shared.createBooksRepository() ) {
    books = Property(_books)
    self.booksRepository = booksRepository
}

2018-11-12 17:06 UTC, acid-wolox commented on Project/Repositories/BooksRepository.swift
> +    //static let host = "http://"
Delete this if you're not using it anymore.

2018-11-12 17:06 UTC, acid-wolox commented on Project/Repositories/BooksRepository.swift
> +class BooksRepository: AbstractRepository,BooksRepositoryType {
Add a space after the comma.

2018-11-13 16:05 UTC, emmanuelhcpk commented on Project/BookDetail/Comments/CommentViewController.swift
> +        super.didReceiveMemoryWarning()
mmm I see it in the kickoff controller so, i put in every viewcontroller, but I will delete it

2018-11-13 17:35 UTC, acid-wolox approved these changes
Awesome!

2018-11-13 18:20 UTC, merged